services:
  - type: web
    name: yard-services
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SECRET_KEY
        generateValue: true
      - key: DB_LOCAL_PATH
        value: yard.db
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        value: yardservices-storage-2
      - key: B2_BUCKET_ID
        value: 6cb12b4a501892429bfe0716
